name:                d7
version:             0.1.0.0
github:              "gqo/d7"
license:             BSD3
author:              "Graeme Ferguson"
maintainer:          "example@example.com"
copyright:           "GNU GPL v3.0"

extra-source-files:
- README.md
- ChangeLog.md

data-files:
- data/ex.txt
- data/input.txt

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/gqo/d7#readme>

dependencies:
- base >= 4.7 && < 5
- split

library:
  source-dirs: src

executables:
  d7-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - d7

tests:
  d7-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - d7
